#!/usr/bin/env python

#    Dicekey. A Diceware password generator.
#    Copyright (C) 2016  Kris Lamoureux
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Built-in
import traceback
import sys

try:
    import dicekey.core

except KeyboardInterrupt:
    print "\nGoodbye!"
    sys.exit(0)

except SystemExit:
    raise

except:
    # Print error then wait to be closed.
    traceback.print_exc()
    raw_input()
    sys.exit(0)
